/**
 * Byte-offset sidecar cache / 字节偏移 sidecar 缓存
 *
 * Stores periodic { uuid → byteOffset } anchors for each session jsonl so
 * parseSessionSlice can seek directly to the cursor's position instead of
 * linear-scanning the file head every page.
 *
 * Self-consistency rule:
 *   Anchors are only valid when the session file's mtimeMs and size match
 *   the values captured when the anchors were written. Any mismatch → ignore.
 *
 * Anchor cadence: every ANCHOR_EVERY (100) messages. Default page size 200
 * means every nextCursor is at message 200/400/600… — which are anchors.
 * 每 100 条采一个锚点；与默认页大小 200 自然对齐
 */

import { promises as fsp, existsSync } from 'fs';
import { dirname } from 'path';
import { logger } from '../utils/logger.js';
import { cachePaths } from '../utils/cache-paths.js';

export const ANCHOR_EVERY = 100;
const SCHEMA_VERSION = 1;

export interface OffsetAnchor {
  uuid: string;
  byteOffset: number;
}

export interface OffsetIndex {
  schemaVersion: number;
  mtimeMs: number;
  size: number;
  anchors: OffsetAnchor[];
}

/**
 * Load the offset sidecar for a session, returning null when the cache is
 * missing, malformed, or stale relative to the source file.
 * 加载 sidecar；缺失或与源文件不一致时返回 null
 */
export async function loadOffsetIndex(
  projectId: string,
  sessionId: string,
  expectedMtimeMs: number,
  expectedSize: number,
): Promise<OffsetIndex | null> {
  const file = cachePaths.offsetFile(projectId, sessionId);
  if (!existsSync(file)) return null;
  try {
    const raw = await fsp.readFile(file, 'utf-8');
    const parsed = JSON.parse(raw) as OffsetIndex;
    if (parsed?.schemaVersion !== SCHEMA_VERSION) return null;
    if (parsed.mtimeMs !== expectedMtimeMs || parsed.size !== expectedSize) return null;
    if (!Array.isArray(parsed.anchors)) return null;
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Atomically persist anchors for a session.
 * 原子化写入 sidecar
 */
export async function saveOffsetIndex(
  projectId: string,
  sessionId: string,
  idx: OffsetIndex,
): Promise<void> {
  const file = cachePaths.offsetFile(projectId, sessionId);
  const tmp = `${file}.tmp.${process.pid}`;
  try {
    await fsp.mkdir(dirname(file), { recursive: true });
    await fsp.writeFile(tmp, JSON.stringify(idx), 'utf-8');
    await fsp.rename(tmp, file);
  } catch (err) {
    logger.error(`offset-cache: save failed for ${projectId}/${sessionId}: ${err}`);
    try { await fsp.unlink(tmp); } catch { /* ignore */ }
  }
}

/**
 * Look up the anchor whose uuid exactly matches the cursor.
 * Anchors generated by us at every ANCHOR_EVERY messages mean default-page
 * cursors land on anchors; non-aligned cursors fall back to filehead scan.
 * 查询完全匹配的锚点；未命中则调用方应回退到全扫
 */
export function findAnchor(idx: OffsetIndex, uuid: string): OffsetAnchor | null {
  for (let i = 0; i < idx.anchors.length; i++) {
    if (idx.anchors[i].uuid === uuid) return idx.anchors[i];
  }
  return null;
}

/**
 * Drop the sidecar from disk (called on file change/unlink so the next reader
 * regenerates fresh anchors).
 * 文件变更或删除时丢弃 sidecar
 */
export async function evictOffsets(projectId: string, sessionId: string): Promise<void> {
  const file = cachePaths.offsetFile(projectId, sessionId);
  if (!existsSync(file)) return;
  try { await fsp.unlink(file); }
  catch (err) { logger.debug(`offset-cache: evict failed: ${err}`); }
}

export function newOffsetIndex(mtimeMs: number, size: number): OffsetIndex {
  return { schemaVersion: SCHEMA_VERSION, mtimeMs, size, anchors: [] };
}
